<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head xmlns="http://www.w3.org/1999/xhtml">
    <title>Catalog</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
</head>
<body>
<? if (@$_SESSION['admin']): ?>
    <div style="margin-bottom: 20px">
        You are authorized as an administrator.
        <a href="/logout">Sign out</a>
    </div>
<? else: ?>
    <div style="margin-bottom: 20px">      
        <a href="/login">Sign in</a>
    </div>  
<? endif ?>

<? if (isset($breadcrumbs)): ?>
    <div id="breadcrumbs">
    <? $i = 0 ?>

    <? foreach ($breadcrumbs as $url => $name): ?>
        <? if ($i++): ?>
            &rarr;
        <? endif ?>    
        <a href="<?= $url ?>"><?= $name ?></a> 

    <? endforeach ?>
    </div>
<? endif ?>
<?= $page_content ?>
</body>
</html>
